Adding api to travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,42 +24,69 @@ env:
   - LASTTAG=$(git describe --tags)
   - TAG="$LASTTAG"
   matrix:
-  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc zip unzip libc6-dev libc6-dev-amd64" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" MAKEJOBS="-j4" WINE=true
-  - HOST=x86_64-pc-linux-gnu PACKAGES="bc python3-zmq zip unzip libc6-dev libc6-dev-amd64" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports --disable-tests" CPPFLAGS="-DDEBUG_LOCKORDER -DENABLE_DASH_DEBUG" PYZMQ=true   
-  - HOST=arm-linux-gnueabihf DEP_OPTS="NO_QT=1" PACKAGES="g++-arm-linux-gnueabihf libc6-dev-armhf-cross" GOAL="install-strip" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports --disable-tests"
-  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc zip unzip libc6-dev-i386" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-reduce-exports --disable-tests"
-  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq zip unzip libc6-dev libc6-dev-i386" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports --disable-tests LDFLAGS=-static-libstdc++" PYZMQ=true
-  - HOST=x86_64-apple-darwin14 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev zip unzip libc6-dev libc6-dev-amd64" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" OSX_SDK=10.9 GOAL="deploy"
+  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-x86-64
+    wine1.6 bc zip unzip libc6-dev libc6-dev-amd64" RUN_TESTS=false GOAL="install-strip"
+    BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" MAKEJOBS="-j4"
+    WINE=true
+  - HOST=x86_64-pc-linux-gnu PACKAGES="bc python3-zmq zip unzip libc6-dev libc6-dev-amd64"
+    RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat
+    --enable-reduce-exports --disable-tests" CPPFLAGS="-DDEBUG_LOCKORDER -DENABLE_DASH_DEBUG"
+    PYZMQ=true
+  - HOST=arm-linux-gnueabihf DEP_OPTS="NO_QT=1" PACKAGES="g++-arm-linux-gnueabihf
+    libc6-dev-armhf-cross" GOAL="install-strip" BITCOIN_CONFIG="--enable-glibc-back-compat
+    --enable-reduce-exports --disable-tests"
+  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686
+    wine1.6 bc zip unzip libc6-dev-i386" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-reduce-exports
+    --disable-tests"
+  - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq zip unzip libc6-dev
+    libc6-dev-i386" RUN_TESTS=false GOAL="install-strip" BITCOIN_CONFIG="--enable-zmq
+    --enable-glibc-back-compat --enable-reduce-exports --disable-tests LDFLAGS=-static-libstdc++"
+    PYZMQ=true
+  - HOST=x86_64-apple-darwin14 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
+    libz-dev libbz2-dev libtiff-tools python-dev zip unzip libc6-dev libc6-dev-amd64"
+    BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests" OSX_SDK=10.9
+    GOAL="deploy"
 before_install:
-  - travis_retry sudo apt-get install python-dev
-  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- travis_retry sudo apt-get install python-dev
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
+  sed "s|::|:|g")
 install:
-  - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
-  - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
+- if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
+- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
+  fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
 before_script:
-  - unset CC; unset CXX
-  - mkdir -p depends/SDKs depends/sdk-sources
-  - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-  - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-  - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+- unset CC; unset CXX
+- mkdir -p depends/SDKs depends/sdk-sources
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
 script:
-  - cd $TRAVIS_BUILD_DIR/depends
-  - make $MAKEJOBS HOST=$HOST $DEP_OPTS
-  - cd $TRAVIS_BUILD_DIR
-  - ./autogen.sh
-  - CONFIG_SITE=$TRAVIS_BUILD_DIR/depends/$HOST/share/config.site ./configure $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG --prefix=$TRAVIS_BUILD_DIR/../3dcoin-$HOST-$TAG
-  - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
+- cd $TRAVIS_BUILD_DIR/depends
+- make $MAKEJOBS HOST=$HOST $DEP_OPTS
+- cd $TRAVIS_BUILD_DIR
+- "./autogen.sh"
+- CONFIG_SITE=$TRAVIS_BUILD_DIR/depends/$HOST/share/config.site ./configure $BITCOIN_CONFIG_ALL
+  $BITCOIN_CONFIG --prefix=$TRAVIS_BUILD_DIR/../3dcoin-$HOST-$TAG
+- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
+  V=1 ; false )
 before_deploy:
-  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
-  - if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv 3DCoin-Core.dmg 3DCoin-Core-$TAG-macosx-generic.dmg; FILE=3DCoin-Core-$TAG-macosx-generic.dmg; else HERE=$(pwd); cd $TRAVIS_BUILD_DIR/../; zip -r $HERE/3dcoin-$TAG-$HOST.zip 3dcoin-$HOST-$TAG; cd $HERE; FILE="3dcoin-$TAG-$HOST.zip"; fi
-  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
+- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
+- if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv 3DCoin-Core.dmg 3DCoin-Core-$TAG-macosx-generic.dmg;
+  FILE=3DCoin-Core-$TAG-macosx-generic.dmg; else HERE=$(pwd); cd $TRAVIS_BUILD_DIR/../;
+  zip -r $HERE/3dcoin-$TAG-$HOST.zip 3dcoin-$HOST-$TAG; cd $HERE; FILE="3dcoin-$TAG-$HOST.zip";
+  fi
+- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
 deploy:
   provider: releases
   api_key:
-    secure: P12DmqIyf6N+DhL5Ia+QGO7IH1Y6Vo4VvTyf5uvU3AFjAxnK02ToYln2t9wEtBmhah7QX+UhzxdQde5GFXhXuWJ7QwL/q8Gafm+RHBdFIB4GX+a+lJamc8zBCW/XzxuoGqa7yX4ogdXgvBFabZABVFwrn2Gk3ajP42Q7jnl4y6kHQ34i3FkAZjaEOhRhnAaEHPG+KAeVDgGFAMfkjg3gIXs5cEgP0rHUiWDRGG/SRE13mzkd5BKQi+2NNpJDuz8rj8W6n/AWXn3IplHrBf0wIu/Rt0CcCMq+5ZiUUfGwqJR5do7I6O91swtoPYi2GATFjriGK/DBrKHbvU4HOeWFBA5DJfYdQRJcZuNhfH5WpvAZjJP/rG+TPCeFXJ5HAbrg6b2TAVjyuy7AYzTK+jHQ2fckL4+MxCBTSWXi0KXO5YneC0x6nZ2tipYPBjIxWbq62dU49b6cl4Mzh+9Cs40gLwHFKQ1NKZQ6XDjdVkF6rKvJNtAWLr54Uza8Orkf5R+5OmQkdDRp7047qnUCAc2c6EzduNv22NyLvcI/7DEYtEBudepV6v1mNEQKn/8xZtnNRBxWUhgLEN9uDNB8BjArCVe7QJdwlbnmyn1J3X5/eUqOP35k0PzoUDtXCq1m9/d0czkRC1jX70KetN3z3F8YBzGnzeQKoPm+GCKqqYfKVnw=
-    file: "$FILE"
+    secure: EE+mLYRe1cEpRrbJ5fEIGpdIalacjhPzbUZGl+Vn1tvmc1EOLjt5xBnRD1WXzWD3aql5XPhNdH2SEJewMwhJWLJCrrS8XjS+SrWLk4ywpRa0y9IcYS0/KuXeIfdAikHlTBrI5OzxM4IB0C4cXE6eSs9ZTS1TVuEU3+6ffR7nsEGnPNTMiJzvP/oh5D+BWD2an34oRCZJJGOecbwQgoySGcnsfw+R7vSOUf5ayAg1Y+XHA71faz2mhUaocMhyLjLg0fRyAe2E8ea4MZcv89zzvDmZFq5LeWfB/fjRnO33akmGbvKKYcFUme1UaZZi8KBWyr7OgvXcwFlIw8arD31ZV1ZXbMtHv0N2KRkSgQnRTJFFQtktMW8XTgmSYqeTipe+/rpHfepDosoZgMPMzCq5H+/xLb02yu0Ezje7O5TtS7bUA1fi7B6ieXro931ca4SxJ7vaw2H7yoJu6YKkHqGOT4evP70mcNCdF3gaAKbK+Wv35jD8/W67Cp0DgLHMDegSXKZHUejAadQ3c5N8QAagroxi91ijiJoFdkjjYSqj+O6wGVGvU5sjNLvJ8MFTx2cyFFVP8MB3O8cM2uXOT1rTkjvaKqAcXvqezsRSqsGZxgold8w9jWVfhXFBSIDk9urxH2AUI4/0JUgqadPRg6/pB+NNBgXmqTYL3CdUmsNeQA8=
+  file: '"$FILE"'
   on:
     repo: ScaMar/3dcoin
     branch: master
